### ISSUE TITLE
Error receiving broadcast Intent

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#127]
```bash
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.SCAN_RESULTS flg=0x4000010 (has extras) } in nl.hnogames.domoticz.Utils.PhoneConnectionUtil$1@423ef878
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:808)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5395)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:655)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.SecurityException: null from uid 10107 not allowed to perform WIFI_SCAN
	at android.os.Parcel.readException(Parcel.java:1465)
	at android.os.Parcel.readException(Parcel.java:1419)
	at android.net.wifi.IWifiManager$Stub$Proxy.getScanResults(IWifiManager.java:1049)
	at android.net.wifi.WifiManager.getScanResults(WifiManager.java:983)
	at nl.hnogames.domoticz.Utils.PhoneConnectionUtil$1.onReceive(PhoneConnectionUtil.java:84)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:798)
	... 9 more

```

**Comment by RoadXY** [comment]
Because the current stable version is 0.1.234, this is old, I guess?

**Comment by RoadXY** [comment]
Closed as old.
