### ISSUE TITLE
java.lang.IllegalArgumentException: You have to override the easygcm_sender_id string resource to provide the GCM sender ID, OR provide it using google services gradle plugin and google-services.json configuration.

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#132]
```bash
java.lang.IllegalArgumentException: You have to override the easygcm_sender_id string resource to provide the GCM sender ID, OR provide it using google services gradle plugin and google-services.json configuration.
	at eu.inloop.easygcm.EasyGcm.getGcmSenderId(EasyGcm.java:197)
	at eu.inloop.easygcm.GcmRegistrationService.registerGcm(GcmRegistrationService.java:64)
	at eu.inloop.easygcm.GcmRegistrationService.onHandleIntent(GcmRegistrationService.java:56)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:155)
	at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by galadril** [comment]
old version./.
