### ISSUE TITLE
java.lang.SecurityException: getDeviceId: Neither user 10447 nor current process has android.permission.READ_PHONE_STATE.

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#146]
```bash
java.lang.SecurityException: getDeviceId: Neither user 10447 nor current process has android.permission.READ_PHONE_STATE.
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.os.Parcel.readException(Parcel.java:1573)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:4207)
	at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:706)
	at nl.hnogames.domoticz.Utils.DeviceUtils.getUniqueID(DeviceUtils.java:35)
	at nl.hnogames.domoticz.app.AppController.sendRegistrationIdToBackend(AppController.java:156)
	at eu.inloop.easygcm.EasyGcm.onSuccessfulRegistration(EasyGcm.java:207)
	at eu.inloop.easygcm.GcmRegistrationService.registerGcm(GcmRegistrationService.java:101)
	at eu.inloop.easygcm.GcmRegistrationService.onHandleIntent(GcmRegistrationService.java:56)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by galadril** [comment]
Debug issue.. close case

**Comment by RoadXY** [comment]
Saw the subject and was really wondering what the issue could be, lol.
Testing GCM, I guess?

**Comment by galadril** [comment]
yep

**Comment by galadril** [comment]
im also going to disable splunk mint for debug :)

**Comment by RoadXY** [comment]
That's a really good idea :+1:
