### ISSUE TITLE
Failure delivering result ResultInfo to MainActivity

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#149]
```bash
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=995, result=-1, data=Intent { (has extras) }} to activity {nl.hnogames.domoticz/nl.hnogames.domoticz.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.SwipeRefreshLayout.setRefreshing(boolean)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4067)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4110)
	at android.app.ActivityThread.access$1400(ActivityThread.java:177)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1498)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.SwipeRefreshLayout.setRefreshing(boolean)' on a null object reference
	at nl.hnogames.domoticz.Fragments.Dashboard.processDashboard(Dashboard.java:134)
	at nl.hnogames.domoticz.Fragments.Dashboard.refreshFragment(Dashboard.java:85)
	at nl.hnogames.domoticz.MainActivity.refreshFragment(MainActivity.java:203)
	at nl.hnogames.domoticz.MainActivity.onActivityResult(MainActivity.java:193)
	at android.app.Activity.dispatchActivityResult(Activity.java:6549)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4063)
	... 10 more

```

**Comment by galadril** [comment]
Already fixed:
"Attempt to invoke virtual method 'void android.support.v4.widget.SwipeRefreshLayout.setRefreshing(boolean)' on a null object reference"

Old exception :-1:
