### ISSUE TITLE
Unable to resume MainActivity NullPointerException

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#154]
```bash
java.lang.RuntimeException: Unable to resume activity {nl.hnogames.domoticz.premium/nl.hnogames.domoticz.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3403)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3434)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at nl.hnogames.domoticz.Domoticz.Domoticz.isUserOnLocalWifi(Domoticz.java:136)
	at nl.hnogames.domoticz.Domoticz.Domoticz.constructGetUrl(Domoticz.java:401)
	at nl.hnogames.domoticz.Domoticz.Domoticz.getDevices(Domoticz.java:896)
	at nl.hnogames.domoticz.Fragments.Switches.getSwitchesData(Switches.java:136)
	at nl.hnogames.domoticz.Fragments.Switches.refreshFragment(Switches.java:93)
	at nl.hnogames.domoticz.MainActivity.refreshFragment(MainActivity.java:203)
	at nl.hnogames.domoticz.MainActivity.onResume(MainActivity.java:471)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
	at android.app.Activity.performResume(Activity.java:6412)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3392)
	... 9 more

```

**Comment by galadril** [comment]
This is already fixed:

```
**class **Domoticz, **method **isUserOnLocalWifi
if (!UsefulBits.isEmpty(currentSsid))
`
