### ISSUE TITLE
java.lang.SecurityException: getDeviceId: Neither user 10448 nor current process has android.permission.READ_PHONE_STATE.

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#177]
```bash
java.lang.SecurityException: getDeviceId: Neither user 10448 nor current process has android.permission.READ_PHONE_STATE.
	at android.os.Parcel.readException(Parcel.java:1608)
	at android.os.Parcel.readException(Parcel.java:1561)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:4175)
	at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:743)
	at nl.hnogames.domoticz.Utils.DeviceUtils.getUniqueID(DeviceUtils.java:36)
	at nl.hnogames.domoticz.app.AppController.sendRegistrationIdToBackend(AppController.java:174)
	at eu.inloop.easygcm.EasyGcm.onSuccessfulRegistration(EasyGcm.java:207)
	at eu.inloop.easygcm.GcmRegistrationService.registerGcm(GcmRegistrationService.java:101)
	at eu.inloop.easygcm.GcmRegistrationService.onHandleIntent(GcmRegistrationService.java:56)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:168)
	at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by galadril** [comment]
Added a check to see if we have permissions

**Comment by sarthak3154** [comment]
@galadril did u solve this issue?

**Comment by abuqauod** [comment]
you have to root the device.
its a system permission
