### ISSUE TITLE
java.lang.RuntimeException: Unable to resume activity {nl.hnogames.domoticz.premium/nl.hnogames.domoticz.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#197]
```bash
java.lang.RuntimeException: Unable to resume activity {nl.hnogames.domoticz.premium/nl.hnogames.domoticz.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3509)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3540)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1518)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6117)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at nl.hnogames.domoticz.Domoticz.Domoticz.isUserOnLocalWifi(Domoticz.java:136)
	at nl.hnogames.domoticz.Domoticz.Domoticz.constructGetUrl(Domoticz.java:401)
	at nl.hnogames.domoticz.Domoticz.Domoticz.getScenes(Domoticz.java:662)
	at nl.hnogames.domoticz.Fragments.Scenes.processScenes(Scenes.java:107)
	at nl.hnogames.domoticz.Fragments.Scenes.refreshFragment(Scenes.java:86)
	at nl.hnogames.domoticz.MainActivity.refreshFragment(MainActivity.java:203)
	at nl.hnogames.domoticz.MainActivity.onResume(MainActivity.java:471)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
	at android.app.Activity.performResume(Activity.java:6495)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3498)
	... 9 more

```

**Comment by galadril** [comment]
already fixed in latest version 

` if (!UsefulBits.isEmpty(currentSsid)) {
                    // Remove quotes from current SSID read out
                    currentSsid = currentSsid.substring(1, currentSsid.length() - 1);
                    for (String ssid : localSsid) {
                        if (ssid.equals(currentSsid)) userIsLocal = true;
                    }
                }`
