### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.setHasAlpha(boolean)' on a null object reference

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#20]
```bash
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.setHasAlpha(boolean)' on a null object reference
	at android.graphics.Bitmap.createBitmap(Bitmap.java:835)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
	at lecho.lib.hellocharts.renderer.LineChartRenderer.onChartSizeChanged(LineChartRenderer.java:72)
	at lecho.lib.hellocharts.renderer.ComboChartRenderer.onChartSizeChanged(ComboChartRenderer.java:25)
	at lecho.lib.hellocharts.view.AbstractChartView.onSizeChanged(AbstractChartView.java:78)
	at android.view.View.sizeChange(View.java:16754)
	at android.view.View.setFrame(View.java:16716)
	at android.view.View.layout(View.java:16633)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at com.afollestad.materialdialogs.internal.MDRootLayout.onLayout(MDRootLayout.java:255)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by galadril** [comment]
Looks like an issue with the library that we use for charts:
  at lecho.lib.hellocharts.renderer.LineChartRenderer.onChartSizeChanged(LineChartRenderer.java:72)
    at lecho.lib.hellocharts.renderer.ComboChartRenderer.onChartSizeChanged(ComboChartRenderer.java:25)

**Comment by RoadXY** [comment]
Yeah looks like it.
Many similar crashes like this one?

**Comment by galadril** [comment]
not so mutch..

**Comment by galadril** [comment]
Haven't seen this exception on Splunk Mint anymore.
I'll reopen this case if it happens again
