### ISSUE TITLE
Unable to resume activity {nl.hnogames.domoticz/nl.hnogames.domoticz.MainActivity}: java.lang.NullPointerException

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#213]
```bash
java.lang.RuntimeException: Unable to resume activity {nl.hnogames.domoticz/nl.hnogames.domoticz.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.SwipeRefreshLayout.setRefreshing(boolean)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3346)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3377)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1466)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5832)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.SwipeRefreshLayout.setRefreshing(boolean)' on a null object reference
	at nl.hnogames.domoticz.Fragments.Temperature.processTemperature(Temperature.java:107)
	at nl.hnogames.domoticz.Fragments.Temperature.refreshFragment(Temperature.java:72)
	at nl.hnogames.domoticz.MainActivity.refreshFragment(MainActivity.java:203)
	at nl.hnogames.domoticz.MainActivity.onResume(MainActivity.java:471)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
	at android.app.Activity.performResume(Activity.java:6338)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3335)
	... 9 more

```

**Comment by galadril** [comment]
Old exception.. code already checks on null for mSwipeRefreshLayout:

`private void processTemperature() {
        if (mSwipeRefreshLayout != null)
            mSwipeRefreshLayout.setRefreshing(true);

        mDomoticz.getTemperatures(new TemperatureReceiver() {
            @Override
            public void onReceiveTemperatures(ArrayList<TemperatureInfo> mTemperatureInfos) {
                successHandling(mTemperatureInfos.toString(), false);
                createListView(mTemperatureInfos);
            }

            @Override
            public void onError(Exception error) {
                errorHandling(error);
            }
        });
    }

    private void cre`
