### ISSUE TITLE
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=885, result=-1, data=Intent { (has extras) }} to activity {nl.hnogames.domoticz.premium/nl.hnogames.domoticz.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=11; index=11

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#228]
```bash
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=885, result=-1, data=Intent { (has extras) }} to activity {nl.hnogames.domoticz.premium/nl.hnogames.domoticz.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=11; index=11
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3742)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3785)
	at android.app.ActivityThread.access$1400(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5525)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=11; index=11
	at nl.hnogames.domoticz.Utils.SharedPrefUtil.getNavigationActions(SharedPrefUtil.java:406)
	at nl.hnogames.domoticz.MainActivity.addDrawerItems(MainActivity.java:284)
	at nl.hnogames.domoticz.MainActivity.drawNavigationMenu(MainActivity.java:164)
	at nl.hnogames.domoticz.MainActivity.buildScreen(MainActivity.java:142)
	at nl.hnogames.domoticz.MainActivity.onActivityResult(MainActivity.java:199)
	at android.app.Activity.dispatchActivityResult(Activity.java:6463)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3738)
	... 9 more

```

**Comment by galadril** [comment]
issue was a swedish translations..

fixed
