### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{nl.hnogames.domoticz/nl.hnogames.domoticz.GraphActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#230]
```bash
java.lang.RuntimeException: Unable to start activity ComponentInfo{nl.hnogames.domoticz/nl.hnogames.domoticz.GraphActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:374)
	at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:369)
	at nl.hnogames.domoticz.Utils.SharedPrefUtil.&lt;init&gt;(SharedPrefUtil.java:110)
	at nl.hnogames.domoticz.Domoticz.Domoticz.&lt;init&gt;(Domoticz.java:115)
	at nl.hnogames.domoticz.Fragments.Graph.getGraphs(Graph.java:128)
	at nl.hnogames.domoticz.Fragments.Graph.onCreateView(Graph.java:117)
	at android.app.Fragment.performCreateView(Fragment.java:2053)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.app.BackStackRecord.run(BackStackRecord.java:834)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
	at android.app.Activity.performStart(Activity.java:6005)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2321)
	... 10 more

```

**Comment by galadril** [comment]
I don;t really get why we have this exceptions..

## sequence of events of a fragment:
    onAttach()
    onCreateView()
    onActivityCreated()
    onDestroyView()
    onDetach()

You get the context in the **onAttach** and we make the SharedPrefs object with this context.
How can that context / sharedprefs be null in the **onCreateView** method??

**Comment by galadril** [comment]
Fixed
