### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setBackground(android.graphics.drawable.Drawable)' on a null object reference

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#252]
```bash
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setBackground(android.graphics.drawable.Drawable)' on a null object reference
	at nl.hnogames.domoticz.Adapters.NotificationsAdapter.getView(NotificationsAdapter.java:87)
	at android.widget.AbsListView.obtainView(AbsListView.java:2349)
	at android.widget.ListView.makeAndAddView(ListView.java:1864)
	at android.widget.ListView.fillDown(ListView.java:698)
	at android.widget.ListView.fillFromTop(ListView.java:759)
	at android.widget.ListView.layoutChildren(ListView.java:1673)
	at android.widget.AbsListView.onLayout(AbsListView.java:2153)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.widget.ScrollView.onLayout(ScrollView.java:1502)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at com.afollestad.materialdialogs.internal.MDRootLayout.onLayout(MDRootLayout.java:255)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)

```

**Comment by galadril** [comment]
Already fixed in latest version
