### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setEnabled(boolean)' on a null object reference

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#258]
```bash
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setEnabled(boolean)' on a null object reference
	at nl.hnogames.domoticz.UpdateActivity$6.onReceiveUpdate(UpdateActivity.java:270)
	at nl.hnogames.domoticz.Domoticz.UpdateVersionParser.parseResult(UpdateVersionParser.java:49)
	at nl.hnogames.domoticz.Utils.RequestUtil$4.onResponse(RequestUtil.java:147)
	at nl.hnogames.domoticz.Utils.RequestUtil$4.onResponse(RequestUtil.java:142)
	at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5373)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

```

**Comment by RoadXY** [comment]
Production and Beta are on 240, Alpha = 248
