### ISSUE TITLE
java.lang.RuntimeException: bad array lengths

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#261]
```bash
java.lang.RuntimeException: bad array lengths
	at android.os.Parcel.readIntArray(Parcel.java:926)
	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:710)
	at android.app.NotificationManager.notify(NotificationManager.java:230)
	at android.app.NotificationManager.notify(NotificationManager.java:194)
	at nl.hnogames.domoticz.Utils.NotificationUtil.sendSimpleNotification(NotificationUtil.java:74)
	at nl.hnogames.domoticz.app.AppController.onMessage(AppController.java:163)
	at eu.inloop.easygcm.EasyGcmListenerService.onMessageReceived(EasyGcmListenerService.java:26)
	at com.google.android.gms.gcm.GcmListenerService.zzq(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zzp(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

```

**Comment by rajanbhavsar001** [comment]
What is the solution for this Issue ?
