### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.getColor(int)' on a null object reference

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#267]
```bash
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.getColor(int)' on a null object reference
	at com.afollestad.materialdialogs.util.DialogUtils.getColor(DialogUtils.java:115)
	at com.afollestad.materialdialogs.MaterialDialog$Builder.&lt;init&gt;(MaterialDialog.java:478)
	at nl.hnogames.domoticz.UI.SwitchLogInfoDialog.&lt;init&gt;(SwitchLogInfoDialog.java:50)
	at nl.hnogames.domoticz.Fragments.Switches.showLogDialog(Switches.java:270)
	at nl.hnogames.domoticz.Fragments.Switches.access$900(Switches.java:69)
	at nl.hnogames.domoticz.Fragments.Switches$7.onReceiveSwitches(Switches.java:342)
	at nl.hnogames.domoticz.Domoticz.SwitchLogParser.parseResult(SwitchLogParser.java:58)
	at nl.hnogames.domoticz.Utils.RequestUtil$7.onResponse(RequestUtil.java:223)
	at nl.hnogames.domoticz.Utils.RequestUtil$7.onResponse(RequestUtil.java:213)
	at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by galadril** [comment]
Updated the library, think we can close this one
