### ISSUE TITLE
java.lang.RuntimeException: Unable to destroy activity {nl.hnogames.domoticz/nl.hnogames.domoticz.MainActivity}: java.lang.IllegalStateException: Observer android.widget.AbsListView$AdapterDataSetObserver@6661965 was not registered.

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#276]
```bash
java.lang.RuntimeException: Unable to destroy activity {nl.hnogames.domoticz/nl.hnogames.domoticz.MainActivity}: java.lang.IllegalStateException: Observer android.widget.AbsListView$AdapterDataSetObserver@6661965 was not registered.
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3865)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3883)
	at android.app.ActivityThread.-wrap5(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5456)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException: Observer android.widget.AbsListView$AdapterDataSetObserver@6661965 was not registered.
	at android.database.Observable.unregisterObserver(Observable.java:69)
	at android.widget.BaseAdapter.unregisterDataSetObserver(BaseAdapter.java:42)
	at com.nhaarman.listviewanimations.BaseAdapterDecorator.unregisterDataSetObserver(BaseAdapterDecorator.java:198)
	at android.widget.AbsListView.onDetachedFromWindow(AbsListView.java:2898)
	at android.view.View.dispatchDetachedFromWindow(View.java:14565)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3071)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4603)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4576)
	at android.view.ViewGroup.removeView(ViewGroup.java:4507)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1167)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
	at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2079)
	at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:235)
	at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:326)
	at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:161)
	at nl.hnogames.domoticz.MainActivity.onDestroy(MainActivity.java:738)
	at android.app.Activity.performDestroy(Activity.java:6422)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3852)
	... 9 more

```

**Comment by RoadXY** [comment]
I have no idea if this is a incident or something serious

**Comment by galadril** [comment]
Seems like an issue with the listviewanimations library.
But in the new (beta) version, we almost don't use that library anymore..
