### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#306]
```bash
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
	at java.util.HashMap$KeyIterator.next(HashMap.java:833)
	at java.util.HashSet.&lt;init&gt;(HashSet.java:76)
	at android.app.SharedPreferencesImpl$EditorImpl.putStringSet(SharedPreferencesImpl.java:315)
	at nl.hnogames.domoticz.Utils.SharedPrefUtil.addReceivedNotification(SharedPrefUtil.java:290)
	at nl.hnogames.domoticz.Utils.NotificationUtil.sendSimpleNotification(NotificationUtil.java:77)
	at nl.hnogames.domoticz.app.AppController.onMessage(AppController.java:163)
	at eu.inloop.easygcm.EasyGcmListenerService.onMessageReceived(EasyGcmListenerService.java:26)
	at com.google.android.gms.gcm.GcmListenerService.zzq(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zzp(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

```

**Comment by galadril** [comment]
Exception for older version numbers
