### ISSUE TITLE
java.lang.IllegalArgumentException: Service not registered: android.speech.SpeechRecognizer$Connection@2fe3d61

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#331]
```bash
java.lang.IllegalArgumentException: Service not registered: android.speech.SpeechRecognizer$Connection@2fe3d61
	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1030)
	at android.app.ContextImpl.unbindService(ContextImpl.java:1839)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:557)
	at android.speech.SpeechRecognizer.destroy(SpeechRecognizer.java:408)
	at nl.hnogames.domoticz.SpeechSettingsActivity.stopRecognition(SpeechSettingsActivity.java:383)
	at nl.hnogames.domoticz.SpeechSettingsActivity.onBackPressed(SpeechSettingsActivity.java:436)
	at android.app.Activity.onKeyUp(Activity.java:2456)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2648)
	at android.app.Activity.dispatchKeyEvent(Activity.java:2707)
	at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:241)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2330)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4026)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3988)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3719)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3880)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2208)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1849)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1840)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2185)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

```

**Comment by MNGsulochana** [comment]
Is there any answer for this,If any one knows update

**Comment by AgNm** [comment]
any update on this?

**Comment by sarath-rp** [comment]
This issue is because you are trying to destroy speech recognizer in a system which has not recognization service. (i.e) **createSpeechRecognizer** might be failed in this case. Use [this](https://developer.android.com/reference/android/speech/SpeechRecognizer#isRecognitionAvailable(android.content.Context)) method before creating and destroying the recognizer.
