### ISSUE TITLE
Unparseable date at nl.hnogames.domoticz.Utils.SessionUtil.parseStringToDate(SessionUtil.java:98)

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#34]
java.text.ParseException: Unparseable date: " Fri, 08 Jan 2016 11:49:05 GMT" (at offset 0)
     at java.text.DateFormat.parse(DateFormat.java:571)
     at nl.hnogames.domoticz.Utils.SessionUtil.parseStringToDate(SessionUtil.java:98)
     at nl.hnogames.domoticz.Utils.SessionUtil.addSessionCookie(SessionUtil.java:114)
     at nl.hnogames.domoticz.Utils.RequestUtil$9.getHeaders(RequestUtil.java:242)
     at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:92)
     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
 java.text.ParseException: Unparseable date: " Fri, 08 Jan 2016 11:49:05 GMT" (at offset 0)
     at java.text.DateFormat.parse(DateFormat.java:571)
     at nl.hnogames.domoticz.Utils.SessionUtil.parseStringToDate(SessionUtil.java:98)
     at nl.hnogames.domoticz.Utils.SessionUtil.addSessionCookie(SessionUtil.java:114)
     at nl.hnogames.domoticz.Utils.RequestUtil$3.getHeaders(RequestUtil.java:109)
     at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:92)
     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)

**Comment by galadril** [comment]
my tests... closed
