### ISSUE TITLE
com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#357]
```bash
com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
	at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1328)
	at nl.hnogames.domoticz.UI.SecurityPanelDialog$1.onReceiveSettings(SecurityPanelDialog.java:116)
	at nl.hnogames.domoticz.Domoticz.SettingsParser.parseResult(SettingsParser.java:48)
	at nl.hnogames.domoticz.Utils.RequestUtil$4.onResponse(RequestUtil.java:147)
	at nl.hnogames.domoticz.Utils.RequestUtil$4.onResponse(RequestUtil.java:142)
	at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

```

**Comment by gronel** [comment]
same errror how you fix this issue

**Comment by gronel** [comment]
`    @Override
    public void onBindViewHolder(final FleetAdapter.MyViewHolder holder, int position){
        Fleet item=fleets.get(position);

        holder.itemView.setOnLongClickListener(new View.OnLongClickListener() {
            @Override
            public boolean onLongClick(View view) {
                    new MaterialDialog.Builder(context.getApplicationContext())
                            .title(R.string.method)
                            .items(R.array.menu_opton)
                            .itemsCallback(new MaterialDialog.ListCallback() {
                                @Override
                                public void onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                                    if(text.equals("Modify"))
                                        editMode(holder.binding.getItem().getPlateno());
                                }
                            })
                            .show();
                return false;
            }
        });

        holder.bind(item);

    }`
