### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.ViewGroup.getContext()' on a null object reference

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#367]
```bash
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.ViewGroup.getContext()' on a null object reference
	at android.support.design.widget.Snackbar.&lt;init&gt;(Snackbar.java:183)
	at android.support.design.widget.Snackbar.make(Snackbar.java:215)
	at nl.hnogames.domoticz.MainActivity$5.onProfileChanged(MainActivity.java:595)
	at com.mikepenz.materialdrawer.AccountHeaderBuilder$7.onItemClick(AccountHeaderBuilder.java:1422)
	at com.mikepenz.materialdrawer.DrawerBuilder$5.onClick(DrawerBuilder.java:1711)
	at com.mikepenz.materialdrawer.DrawerBuilder$5.onClick(DrawerBuilder.java:1685)
	at com.mikepenz.fastadapter.FastAdapter$1.onClick(FastAdapter.java:422)
	at android.view.View.performClick(View.java:5697)
	at android.view.View$PerformClick.run(View.java:22526)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

**Comment by BAvinash** [comment]
same problem !!!!
