### ISSUE TITLE
java.lang.RuntimeException: Unable to resume activity {nl.hnogames.domoticz/nl.hnogames.domoticz.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void nl.hnogames.domoticz.Domoticz.Domoticz.getDevices(nl.hnogames.domoticz.Interfaces.DevicesReceiver, int, java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#57]
```bash
java.lang.RuntimeException: Unable to resume activity {nl.hnogames.domoticz/nl.hnogames.domoticz.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void nl.hnogames.domoticz.Domoticz.Domoticz.getDevices(nl.hnogames.domoticz.Interfaces.DevicesReceiver, int, java.lang.String)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3050)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3081)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1395)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5373)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void nl.hnogames.domoticz.Domoticz.Domoticz.getDevices(nl.hnogames.domoticz.Interfaces.DevicesReceiver, int, java.lang.String)' on a null object reference
	at nl.hnogames.domoticz.Fragments.Switches.getSwitchesData(Switches.java:120)
	at nl.hnogames.domoticz.Fragments.Switches.refreshFragment(Switches.java:84)
	at nl.hnogames.domoticz.MainActivity.refreshFragment(MainActivity.java:180)
	at nl.hnogames.domoticz.MainActivity.onResume(MainActivity.java:448)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1262)
	at android.app.Activity.performResume(Activity.java:6120)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3039)
	... 9 more

```

**Comment by galadril** [comment]
old exception
