### ISSUE TITLE
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{c28c8c7 V.E..... R......D 0,0-466,232} not attached to window manager

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#59]
```bash
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{c28c8c7 V.E..... R......D 0,0-466,232} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:341)
	at android.app.Dialog.dismiss(Dialog.java:324)
	at nl.hnogames.domoticz.Fragments.Dashboard.hideProgressDialog(Dashboard.java:573)
	at nl.hnogames.domoticz.Fragments.Dashboard.createListView(Dashboard.java:255)
	at nl.hnogames.domoticz.Fragments.Dashboard.processDevices(Dashboard.java:158)
	at nl.hnogames.domoticz.Fragments.Dashboard.access$000(Dashboard.java:54)
	at nl.hnogames.domoticz.Fragments.Dashboard$1.onReceiveDevices(Dashboard.java:127)
	at nl.hnogames.domoticz.Domoticz.DevicesParser.parseResult(DevicesParser.java:77)
	at nl.hnogames.domoticz.Utils.RequestUtil$7.onResponse(RequestUtil.java:150)
	at nl.hnogames.domoticz.Utils.RequestUtil$7.onResponse(RequestUtil.java:140)
	at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

```

**Comment by galadril** [comment]
old exception
