### ISSUE TITLE
Help to compile and run the app

### ISSUE THREAD

**Issue by nonameboy007** [domoticz/domoticz-android#645]
Hi, first of all thanks for your app , its really cool !

i m trying to compile and run the app on a virtual device, 

For compilation, i think its good, 

but when i start the app, its crashing.

You will find bellow the encountered error with the debug app:

`
01/27 01:03:35: Launching 'app' on Pixel 5 API 30.
Install successfully finished in 3 s 721 ms.
$ adb shell am start -n "nl.hnogames.domoticz.premium/nl.hnogames.domoticz.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: nl.hnogames.domoticz.premium
Waiting for application to come online: nl.hnogames.domoticz.premium
Waiting for application to come online: nl.hnogames.domoticz.premium
Connecting to nl.hnogames.domoticz.premium
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application nl.hnogames.domoticz.premium is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
Connected to the target VM, address: 'localhost:33675', transport: 'socket'
I/System.out: waiting for debugger to settle...
I/chatty: uid=10128(nl.hnogames.domoticz.premium) identical 1 line
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/chatty: uid=10128(nl.hnogames.domoticz.premium) identical 2 lines
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1499)
I/omoticz.premiu: The ClassLoaderContext is a special shared library.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/MultiDex: VM with version 2.1.0 has multidex support
I/MultiDex: Installing application
I/MultiDex: VM has multidex support, MultiDex support library is disabled.
I/MultiDex: Installing application
I/MultiDex: VM has multidex support, MultiDex support library is disabled.
I/FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
I/DynamiteModule: Considering local module com.google.android.gms.flags:3 and remote module com.google.android.gms.flags:3
I/DynamiteModule: Selected local version of com.google.android.gms.flags
I/FirebaseCrashlytics: Initializing Firebase Crashlytics 18.2.1 for nl.hnogames.domoticz.premium
W/DynamiteModule: Local module descriptor class for com.google.android.gms.crash not found.
I/DynamiteModule: Considering local module com.google.android.gms.crash:0 and remote module com.google.android.gms.crash:215
I/DynamiteModule: Selected remote version of com.google.android.gms.crash, version >= 215
V/DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
I/TetheringManager: registerTetheringEventCallback:nl.hnogames.domoticz.premium
I/DynamiteModule: Considering local module com.google.android.gms.measurement.dynamite:51 and remote module com.google.android.gms.measurement.dynamite:13
I/DynamiteModule: Selected local version of com.google.android.gms.measurement.dynamite
W/omoticz.premiu: Unsupported class loader
I/FirebaseInitProvider: FirebaseApp initialization successful
D/AndroidRuntime: Shutting down VM
W/omoticz.premiu: Unsupported class loader
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: nl.hnogames.domoticz.premium, PID: 8997
    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * Invalid application ID. Follow instructions here:                          *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to find your app ID.                                                       *
    ******************************************************************************
    
    
        at android.app.ActivityThread.installProvider(ActivityThread.java:7244)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * Invalid application ID. Follow instructions here:                          *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to find your app ID.                                                       *
    ******************************************************************************
    
    
        at com.google.android.gms.internal.ads.zzzx.attachInfo(com.google.android.gms:play-services-ads-lite@@19.8.0:24)
        at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@19.8.0:3)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7239)
        	... 10 more
I/FirebaseCrashApiImpl: FirebaseCrashApiImpl created by ClassLoader ax[DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/00000004/DynamiteModulesC.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000004/n/x86, /data/user_de/0/com.google.android.gms/app_chimera/m/00000004/n/armeabi-v7a, /data/user_de/0/com.google.android.gms/app_chimera/m/00000004/n/armeabi, /system/lib, /system_ext/lib]]]
I/FirebaseCrash: FirebaseCrash reporting loaded - com.google.android.gms.internal.crash.zzo@9db5ef3
I/DynamiteModule: Considering local module com.google.android.gms.flags:3 and remote module com.google.android.gms.flags:3
I/DynamiteModule: Selected local version of com.google.android.gms.flags
W/FirebaseCrashlytics: Skipping session finalization because a crash has already occurred.
W/FirebaseCrashlytics: Previous sessions could not be finalized.
W/DynamiteModule: Local module descriptor class for com.google.android.gms.crash not found.
V/FA: App measurement collection enabled
V/FA: App measurement enabled for app package, google app id: nl.hnogames.domoticz.premium, 1:705545900899:android:a4327c5a10906b46
I/FA: App measurement initialized, version: 42097
I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app nl.hnogames.domoticz.premium
D/FA: Debug-level message logging enabled
I/FirebaseCrashApiImpl: FirebaseCrash reporting API initialized
I/FirebaseCrash: FirebaseCrash reporting initialized com.google.android.gms.internal.crash.zzo@9db5ef3
D/FirebaseCrash: Firebase Analytics Listener for Firebase Crash is initialized
V/FA: Persisting first open: 1643241826805
V/FA: App measurement setting deferred collection: false
V/FA: Checking service availability
W/GooglePlayServicesUtil: nl.hnogames.domoticz.premium requires the Google Play Store, but it is missing.
W/FA: Service invalid
V/FA: Using local app measurement service
V/FA: Detected application was in foreground
V/FA: Session started, time: 5921236
V/FA: Connection attempt already in progress
I/FA: Tag Manager is not found and thus will not be used
V/FA: Connection attempt already in progress
I/chatty: uid=10128(nl.hnogames.domoticz.premium) Measurement Wor identical 1 line
V/FA: Connection attempt already in progress
E/FirebaseCrashlytics: Error handling uncaught exception
    java.util.concurrent.TimeoutException
        at com.google.firebase.crashlytics.internal.common.Utils.awaitEvenIfOnMainThread(Utils.java:122)
        at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:232)
        at com.google.firebase.crashlytics.internal.common.CrashlyticsController$1.onUncaughtException(CrashlyticsController.java:155)
        at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:54)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
E/UncaughtException: java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * Invalid application ID. Follow instructions here:                          *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to find your app ID.                                                       *
    ******************************************************************************
    
    
        at android.app.ActivityThread.installProvider(ActivityThread.java:7244)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * Invalid application ID. Follow instructions here:                          *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to find your app ID.                                                       *
    ******************************************************************************
    
    
        at com.google.android.gms.internal.ads.zzzx.attachInfo(com.google.android.gms:play-services-ads-lite@@19.8.0:24)
        at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@19.8.0:3)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7239)
        	... 10 more
V/FA: Connection attempt already in progress
E/FirebaseCrash: Failed to report uncaught exception
    java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
        at aqi.a(:com.google.android.gms.dynamite_dynamitemodulesc@201817052@20.18.17 (040700-0):164)
        at com.google.firebase.crash.internal.api.FirebaseCrashApiImpl.a(:com.google.android.gms.dynamite_dynamitemodulesc@201817052@20.18.17 (040700-0):2)
        at com.google.firebase.crash.internal.api.FirebaseCrashApiImpl.reportUncaughtException(:com.google.android.gms.dynamite_dynamitemodulesc@201817052@20.18.17 (040700-0):2)
        at apv.a(:com.google.android.gms.dynamite_dynamitemodulesc@201817052@20.18.17 (040700-0):10)
        at mi.onTransact(:com.google.android.gms.dynamite_dynamitemodulesc@201817052@20.18.17 (040700-0):4)
        at android.os.Binder.transact(Binder.java:1043)
        at com.google.android.gms.internal.crash.zza.transactAndReadExceptionReturnVoid(Unknown Source:20)
        at com.google.android.gms.internal.crash.zzn.zzb(Unknown Source:18)
        at com.google.android.gms.internal.crash.zzg.zzd(Unknown Source:13)
        at com.google.android.gms.internal.crash.zzc.run(Unknown Source:12)
        at com.google.android.gms.internal.crash.zzg.run(Unknown Source:15)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
I/Process: Sending signal. PID: 8997 SIG: 9
Disconnected from the target VM, address: 'localhost:33675', transport: 'socket'
`

does i missed something?

Thanks

**Comment by galadril** [comment]
******************************************************************************
* Invalid application ID. Follow instructions here:                          *
* https://googlemobileadssdk.page.link/admob-android-update-manifest         *
* to find your app ID.                                                       *
******************************************************************************

Youll probably need to setup a Firebase project and hook it up to your project via a config json.
See docs Firebase
