### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{nl.hnogames.domoticz.premium/nl.hnogames.domoticz.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'double com.google.android.gms.maps.model.LatLng.latitude' on a null object reference

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#66]
```bash
java.lang.RuntimeException: Unable to start activity ComponentInfo{nl.hnogames.domoticz.premium/nl.hnogames.domoticz.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'double com.google.android.gms.maps.model.LatLng.latitude' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to read from field 'double com.google.android.gms.maps.model.LatLng.latitude' on a null object reference
	at nl.hnogames.domoticz.Containers.LocationInfo.toGeofence(LocationInfo.java:98)
	at nl.hnogames.domoticz.Utils.SharedPrefUtil.setGeoFenceService(SharedPrefUtil.java:735)
	at nl.hnogames.domoticz.MainActivity.buildScreen(MainActivity.java:117)
	at nl.hnogames.domoticz.MainActivity.onCreate(MainActivity.java:109)
	at android.app.Activity.performCreate(Activity.java:6251)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	... 9 more

```

**Comment by galadril** [comment]
Should be fixed by:
https://github.com/domoticz/domoticz-android/commit/9ea23c298abbc8ffe64d327fb7ec09edf021f602

**Comment by galadril** [comment]
https://github.com/domoticz/domoticz-android/commit/9ea23c298abbc8ffe64d327fb7ec09edf021f602
