### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#87]
```bash
java.lang.RuntimeException: Unable to resume activity {nl.hnogames.domoticz/nl.hnogames.domoticz.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4047)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4078)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1731)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6897)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at nl.hnogames.domoticz.Domoticz.Domoticz.isUserOnLocalWifi(Domoticz.java:117)
	at nl.hnogames.domoticz.Domoticz.Domoticz.constructGetUrl(Domoticz.java:357)
	at nl.hnogames.domoticz.Domoticz.Domoticz.getDevices(Domoticz.java:750)
	at nl.hnogames.domoticz.Fragments.Switches.getSwitchesData(Switches.java:120)
	at nl.hnogames.domoticz.Fragments.Switches.refreshFragment(Switches.java:84)
	at nl.hnogames.domoticz.MainActivity.refreshFragment(MainActivity.java:180)
	at nl.hnogames.domoticz.MainActivity.onResume(MainActivity.java:448)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1271)
	at android.app.Activity.performResume(Activity.java:6671)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4036)
	... 9 more

```

**Comment by RoadXY** [comment]
Beta, master and Alpha branch should be there same code as in the Play Store, shouldn't it?
