### ISSUE TITLE
java.lang.IllegalArgumentException: Can only use lower 8 bits for requestCode

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#92]
```bash
java.lang.IllegalArgumentException: Can only use lower 8 bits for requestCode
	at android.support.v4.app.FragmentActivity.requestPermissionsFromFragment(FragmentActivity.java:868)
	at android.support.v4.app.FragmentActivity.access$000(FragmentActivity.java:79)
	at android.support.v4.app.FragmentActivity$HostCallbacks.onRequestPermissionsFromFragment(FragmentActivity.java:913)
	at android.support.v4.app.Fragment.requestPermissions(Fragment.java:1018)
	at nl.hnogames.domoticz.Fragments.Cameras$1$1.onItemClick(Cameras.java:108)
	at nl.hnogames.domoticz.Adapters.CamerasAdapter$DataObjectHolder.onClick(CamerasAdapter.java:109)
	at android.view.View.performClick(View.java:5204)
	at android.view.View$PerformClick.run(View.java:21156)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5466)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)

```

**Comment by galadril** [comment]
... i don't really see how this could give a problem..


 mAdapter.setOnItemClickListener(new CamerasAdapter.onClickListener() {
                    @Override
                    public void onItemClick(int position, View v) {
                        ImageView cameraImage = (ImageView) v.findViewById(R.id.image);
                        TextView cameraTitle = (TextView) v.findViewById(R.id.name);
                        Bitmap savePic = ((BitmapDrawable) cameraImage.getDrawable()).getBitmap();

                        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                            if (!PermissionsUtil.canAccessStorage(getActivity())) {
                                requestPermissions(PermissionsUtil.INITIAL_STORAGE_PERMS, PermissionsUtil.INITIAL_CAMERA_REQUEST);
                            } else
                                processImage(savePic, (String) cameraTitle.getText());
                        } else {
                            processImage(savePic, (String) cameraTitle.getText());
                        }
                    }
                });

**Comment by RoadXY** [comment]
http://stackoverflow.com/questions/33331073/android-what-to-choose-for-requestcode-values

The following are code from android.support.v4.app.FragmentActivity
@Override
public final void validateRequestPermissionsRequestCode(int requestCode) {
    // We use 8 bits of the request code to encode the fragment id when
    // requesting permissions from a fragment. Hence, requestPermissions()
    // should validate the code against that but we cannot override it as
    // we can not then call super and also the ActivityCompat would call
    // back to this override. To handle this we use dependency inversion
    // where we are the validator of request codes when requesting
    // permissions in ActivityCompat.
    if (mRequestedPermissionsFromFragment) {
        mRequestedPermissionsFromFragment = false;
    } else if ((requestCode & 0xffffff00) != 0) {
        throw new IllegalArgumentException("Can only use lower 8 bits for requestCode");
    }
}

**Comment by galadril** [comment]
mmn.. this should be fixed on beta branch

**Comment by galadril** [comment]
Fixed
