### ISSUE TITLE
java.lang.AssertionError: libcore.io.ErrnoException: getsockname failed: EINVAL (Invalid argument)

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#97]
```bash
java.lang.AssertionError: libcore.io.ErrnoException: getsockname failed: EINVAL (Invalid argument)
	at libcore.io.IoBridge.getSocketLocalAddress(IoBridge.java:586)
	at java.net.Socket.cacheLocalAddress(Socket.java:950)
	at java.net.Socket.connect(Socket.java:844)
	at libcore.net.http.HttpConnection.&lt;init&gt;(HttpConnection.java:76)
	at libcore.net.http.HttpConnection.&lt;init&gt;(HttpConnection.java:50)
	at libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:340)
	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:87)
	at libcore.net.http.HttpConnection.connect(HttpConnection.java:128)
	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:316)
	at libcore.net.http.HttpEngine.connect(HttpEngine.java:311)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:282)
	at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
	at com.splunk.mint.network.http.MonitorableHttpURLConnection.getResponseCode(MonitorableHttpURLConnection.java:362)
	at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:109)
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
Caused by: libcore.io.ErrnoException: getsockname failed: EINVAL (Invalid argument)
	at libcore.io.Posix.getsockname(Native Method)
	at libcore.io.ForwardingOs.getsockname(ForwardingOs.java:72)
	at libcore.io.IoBridge.getSocketLocalAddress(IoBridge.java:582)
	... 17 more

```

**Comment by RoadXY** [comment]
Right.
Looks like a crash in VolleyUtil?

**Comment by RoadXY** [comment]
@galadril Can you check if this is still occurring?

**Comment by galadril** [comment]
dont think so
